### ISSUE TITLE
Just upgraded to 0.1.8 and now partials can't be found?

### ISSUE THREAD

**Issue by KingScooty** [assemble/gulp-assemble#11]
Has anything drastic changed in the API between Assemble 0.5.0 and 0.6.0 for this to happen?

`{{ header }}` renders `[Object object]` in my rendered templates, and `{{> header}}` produces the following error `Error: The partial header could not be found`.

Everything was working fine before i upgraded. Any ideas?

This is my config:

```
var options = {
  layout:    'default.hbs',
  partials:  'app/templates/partials/*.hbs',
  layoutdir: 'app/templates/layouts/',
  data:      'app/data/*.json'
};

gulp.task('assemble', function () {
  gulp.src('app/templates/pages/*.hbs')
    .pipe(assemble(options))
    .pipe(gulp.dest('app/'));
});
```

**Comment by doowb** [comment]
Updates to assemble and gulp-assemble. Try 0.2.0 and reopen if you're still having issues.
