### ISSUE TITLE
Options spread to multiple gulp-assemble tasks due to shared instance

### ISSUE THREAD

**Issue by nicluo** [assemble/gulp-assemble#15]
// Common Config
    var assembleCommonOptions = {
      layouts: ['templates/layouts/*.hbs'],
      partials: ['templates/partials/*.hbs'],
    };
    
    // Specific Config
    var assembleOptions = _.extend({
      layout: 'default',
    }, assembleCommonOptions);

    var assembleOptionsAdmin = _.extend({
      layout: 'admin',
    }, assembleCommonOptions);

    // Assemble Task 1
    gulp.task('assemble-main', function () {
      return gulp.src('templates/pages/*.hbs')
        .pipe(assemble(assembleOptions))
        .pipe(htmlmin())
        .pipe(gulp.dest('dist/'));
    });

    // Assemble Task 2
    gulp.task('assemble-admin', function () {
      return gulp.src('templates/pages/admin/*.hbs')
        .pipe(assemble(assembleOptionsAdmin))
        .pipe(htmlmin())
        .pipe(gulp.dest('dist/admin/'));
    });

I have a site which has multiple assemble tasks.

Running both tasks simultaneously creates problems on the options. In destination directories, files overlap as well (e.g. files from <code>assemble-main</code> may end up in <code>dist/admin</code> depending on the running order).

Previously (0.1.7), I could workaround by using run-sequence, which keeps the options separated long enough for both tasks to work fine.

    gulp.task('assemble', function(callback){
      runSequence(
        'assemble-main',
        'assemble-admin',
        callback);
    });

This does not work anymore in 0.1.8. I'm essentially trying to make the gulp task idempotent.

While exposing the instance in module.exports helps with configuring, I can't really reload the instance between tasks.

    /**
     * Expose instance of assemble for further modification
     */

    plugin.instance = assemble;

In the end, I did this as a quick fix:

    var plugin = module.exports = function (options) {

      assemble = assemble.createInst();

      var opts = _.extend({}, options);
    ...

1 - Is there a better way to do this that I missed?
2 - If you need more information/ minimum code to reproduce I'm more than happy to help. Thanks

**Comment by doowb** [comment]
gulp-assemble 0.2.0 now requires passing in an instance of assemble so you can create new instances for each task. Check out [assemble 0.6.0 docs](https://github.com/assemble/assemble/tree/v0.6.0) for more information.
