### ISSUE TITLE
Running assemble just spits out my .hbs file again.

### ISSUE THREAD

**Issue by jerome-toole** [assemble/gulp-assemble#18]
**After running assemble, I end up with my .hbs file in the destination folder instead of .html.**

The file that is spat out is exactly the same as my original handlebars file except it is missing the sections where I use '{{#each'.

Have just got my project set up on my new laptop (switching from pc to mac) and the gulpfile and everything is the same. I can't think of anything that would have changed and yet this error occurs.

Here is my assemble section of the gulpfile
```javascript
// Assemble templates

var options = {
    data: 'data/*/**.{json,yml}',
    partials: ['data/partials/*.md', '*.hbs'],
    layoutdir: '*.hbs',
};

gulp.task('assemble', function() {
    gulp.src('*.hbs')
        .pipe(plugins.assemble(options))
        .pipe(gulp.dest('./html/'));
});
```

Any help would be really appreciated.

**Comment by doowb** [comment]
You might have had a previous commit of assemble installed on your old machine. There have been changes to assemble that haven't been updated here. This repo isn't ready to be used. Please take a look at [assemble 0.6.0](https://github.com/assemble/assemble/tree/v0.6.0). You might be able to use that directly for now.

**Comment by jerome-toole** [comment]
Ok. thank you. Do you think you could help me understand how I would use regular assemble with gulp?

**Comment by doowb** [comment]
Try using the new version of gulp-assemble (0.2.0) and take a look at [assemble 0.6.0 docs](https://github.com/assemble/assemble/tree/v0.6.0) on how to setup data. If you're still having issues, please reopen.

**Comment by r4fx** [comment]
I have the same problem after update to v 0.6.0. Instead of .html assemble generates duplicate .hbs files in destination folder. It seems like the options being ignored.
I'm using gulp-assemble 0.2.3 and assemble 0.6.0.

this is my configuration:

```js
var gulp = require('gulp');
var assemble = require('assemble');
var gulpAssemble = require('gulp-assemble');

/* Configuration
 / ===========================================*/
var paths = {
    sources: {
        pages: 'doc/src/pages/**/*.hbs'
    },
    build: {
        www: 'doc/www/'
    }
};

// Task
gulp.task('assemble', function () {
    var options = {
        layout: 'default.hbs',
        layoutdir: 'doc/src/layouts',
        partials: 'doc/src/partials/**/*.hbs',
        data: 'doc/src/data/*.{json,yml}'
    };

    gulp.src(paths.sources.pages)
        .pipe(gulpAssemble(assemble, options))
        .pipe(gulp.dest(paths.build.www));
});
```

Any help would be really appreciated.

**Comment by jonschlinkert** [comment]
this is because we don't automatically rename file extensions anymore, to try to be more inline with gulp convention. try using [gulp-extname](https://github.com/jonschlinkert/gulp-extname). It probably won't need any configuration. You could also use gulp-rename or whatever plugin you like for renaming.

**Comment by r4fx** [comment]
Thanks @jonschlinkert it helped to generate html files, but I still wonder why my default layout which contains `{% body %}` tag is ignored and generated html files have the same content like .hbs files, the only difference is that .html files do not have YAML data section.

**Comment by jonschlinkert** [comment]
> but I still wonder why my default layout which contains {% body %} tag is ignored and generated html files have the same content like .hbs files,

maybe we should create a separate issue, sounds unrelated to the OP

**Comment by r4fx** [comment]
naturally -> #21
