### ISSUE TITLE
Data files don't seem to be namespaced, loading straight into global

### ISSUE THREAD

**Issue by KingScooty** [assemble/gulp-assemble#19]
Annoyingly, data files (.json/,yaml) don't seem to be getting namespaced.

I have multiple json files, and they all seem to be getting loaded globally,  regardless of whether there's a template name that matches the data filename.

So if i have several data files with an object of `person` in, i'm only getting the person object from the last data file in the data folder. There's no way to access any of the files via the filename namespace.

Any ideas?

**Comment by doowb** [comment]
Assemble has changed and this repo hasn't been updated to reflect those changes yet. When this repo is updated, I think we'll allow passing in your own instance of assemble which will allow you to load data directly and not have to worry about gulp-assemble trying to map things properly.

This repo isn't ready yet. Check out [assemble 0.6.0](https://github.com/assemble/assemble/tree/v0.6.0) to see if you can use that directly for now.

**Comment by doowb** [comment]
gulp-assemble 0.2.0 now takes an instance of assemble 0.6.0 so you can configure it directly. Take a look at the [assemble 0.6.0 docs](https://github.com/assemble/assemble/tree/v0.6.0) for data configuration.
