### ISSUE TITLE
Changes to Partials/Layouts not being applied on gulp.watch

### ISSUE THREAD

**Issue by johjacb** [assemble/gulp-assemble#24]
When I run ```gulp assemble```, layouts, partials and pages work as expected.

Running ```gulp.watch```, when I make a change to a partial or layout, the change is registered, and gulp runs ```assemble```, but the pages are not changed. Changes to pages, however, are working normally. 

I feel like I am missing something very easy!

Here are the relevant portions of my gulpfile:
```
assemble.partials(['./src/templates/partials/*.hbs']);
assemble.layouts(['./src/templates/layouts/*.hbs']);

gulp.task('assemble', function(){
	gulp.src(['./src/templates/pages/*.hbs'])
		.pipe($.assemble(assemble))
		.pipe($.rename({
			extname: ".html"
		}))
		.pipe(gulp.dest(outputDir + ''))
		.pipe(reload({stream:true}));
})

gulp.watch('./src/templates/**/*.hbs', ['assemble']);
```

Running gulp-assemble 0.3.2 and assemble 0.6.0-beta.4.

Thanks!

**Comment by doowb** [comment]
you need to reload the partials and layouts by moving these lines:

```js
assemble.partials(['./src/templates/partials/*.hbs']);
assemble.layouts(['./src/templates/layouts/*.hbs']);
```

to inside the `task` function just before `src`.

**Comment by johjacb** [comment]
Awesome thank you! Knew it was something simple.
