### ISSUE TITLE
Is assemble removing the comments within the partials? Or is htmlmin doing that? 

### ISSUE THREAD

**Issue by guntherkoo** [assemble/gulp-assemble#36]
Can't figure out what's removing the comments, my default layout hbs still has comments I left.. but anything in partials, all my comments are gone. 

Is this something I can turn off? 

Thanks for your help! The client I'm building for, requires me to leave comments in the HTML.

**Comment by doowb** [comment]
Most likely it's htmlmin. Have you tried setting the `removeComments: false` option for htmlmin? If that doesn't work, will you post your gulp file so we can get a better look?

**Comment by guntherkoo** [comment]
@doowb thanks for the quick response! I figured it out, it was because all the comments I left in hbs files were all handlebars comment line and not html comment line. 

Too use to pressing cmd + / to comment out stuff that it was just commenting based on handlebars and not html. 

Thanks anyway!

**Comment by doowb** [comment]
:grinning: glad you figured it out.
