### ISSUE TITLE
Build stops when using AngularJS pipe

### ISSUE THREAD

**Issue by pburtchaell** [assemble/gulp-assemble#7]
I have the following code in a page:

```
<span>\{{item.description | truncate}}</span>
```

When I run assemble, I get the following error: 

```
Error: Parse error on line 12:
...>{{item.description | truncate }}</span>
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'NUMBER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'DATA', 'SEP', got 'INVALID'
```

I don't understand this error because I did escape the expression. Is this a bug?

[Entire output](https://gist.github.com/pburtchaell/9a1160fd70d708356a57).

**Comment by doowb** [comment]
Closing due to changes with assemble and gulp-assemble. If this is still an issue in assemble 0.6.0, please open the issue there.
