### ISSUE TITLE
Data not passed to templates

### ISSUE THREAD

**Issue by jakemmarsh** [assemble/gulp-assemble#8]
My options object looks like this:
```
var assembleOptions = {
  data:      'public/data/*.json',
  helpers:   'public/helpers/*.js',
  partials:  'public/templates/partials/*.hbs',
  layoutdir: 'public/templates/layouts/'
};
```

My Gulp task looks like this:
```
gulp.task('assemble', function() {

  // Run assemble on static pages
  return gulp.src('./public/pages/**/*.hbs')
          .pipe(assemble(assembleOptions))
          .pipe(htmlmin())
          .pipe(gulp.dest('build/'));

});
```

Everything is working, except any of my data files don't seem to be accessible by the templates. Here is `team.json`, inside the data folder:
```
[
  {
    "name": "Jane Doe",
    "title": "CEO"
  },
  {
    "name": "John Doe",
    "title": "COO"
  }
]
```

I'm then attempting to access this in one of my templates with either `{#each team}` or `{#each data.team}` and have had no luck either way. I've seen other people mention having the same problem within other open issues

**Comment by doowb** [comment]
We've updated assemble and gulp-assemble. Load data directly with `assemble.data(...)`. See [assemble 0.6.0 docs](https://github.com/assemble/assemble/tree/v0.6.0) for more information.
